apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 827964244606.dkr.ecr.us-west-1.amazonaws.com/node-app:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080